---
title: 'Assignment 2: Angrist & Evans AER 1998'
author: "Nathan Franz"
date: "3/7/2020"
output: pdf_document
---


```{r setup, include=F}
library(data.table)
library(stargazer)
library(haven)

setwd('~/UT Courses/3. Spring 2019/Causal Inference/CausalInferenceCourseHomework/Assignment2_IV')
pums80 <- as.data.table(read_dta('data/pums80.dta'))
```





# Summary of Angrist's and Evans' Project

# Replication

## Replicated Tables

```{r results='asis', echo=FALSE}
# make a table of fertility and labor supply measures of the women

pums80_3pluskids <- pums80[pums80$kidcount > 2,]


row_names_column_1 <- c('Mean children ever born',
                      'Percent with more than 2 children',
                      'Percent worked last year',
                      'Observations')
values_column_1 <- c(round(mean(pums80$kidcount), 2),
                   round(nrow(pums80_3pluskids)/nrow(pums80)*100, 2),
                   round(sum(pums80$workedm)/nrow(pums80)*100, 2),
                   nrow(pums80)
                  )

characteristics_table_1 <- data.frame('PUMS 1980' = values_column_1)
row.names(characteristics_table_1) <- row_names_column_1

stargazer(
  characteristics_table_1, 
  header = FALSE,
  summary = FALSE, 
  style = 'AER',
  title = 'Fertility and Labor-Supply Measures, 1980 PUMS Data',
  covariate.labels = c('Married women aged 21–35 with 2 or more children', ''),
  notes = c('Notes: This data includes women with two or more children', 'except for women whose second birth was less than a year old', 'at the time of survey.')
)
```

```{r results='asis', echo=FALSE}

# make a table of descriptive statistics of the women

pums80$threepluskids <- as.numeric(eval(pums80$kidcount >= 3))
pums80$twoboys <- as.numeric(eval(pums80$boy1st + pums80$boy2nd == 2))
pums80$twogirls <- as.numeric(eval(pums80$boy1st + pums80$boy2nd == 0))




row_names_column_2 <- c('Children ever born',
                      '',
                      'More than 2 children',
                      '        ',
                      'Boy 1st',
                      '  ',
                      'Boy 2nd',
                      '   ',
                      'Two boys',
                      '    ',
                      'Two girls',
                      '     ',
                      'Same sex',
                      '      ',
                      'Twins-2',
                      '       ',
                      'Age',
                      ' ',
                      'Age at first birth',
                      '         ',
                      'Worked for pay',
                      '          ',
                      'Weeks worked',
                      '           ',
                      'Hours/week',
                      '            ',
                      'Labor income',
                      '             ',
                      'Number of observations')
values_column_2 <- c(round(mean(pums80$kidcount), 2),
                   paste('(', round(sd(pums80$kidcount), 3), ')', sep=''),
                   round(mean(pums80$threepluskids), 3),
                   paste('(', round(sd(pums80$threepluskids), 3), ')', sep=''),
                   round(mean(pums80$boy1st), 3),
                   paste('(', round(sd(pums80$boy1st), 3), ')', sep=''),
                   round(mean(pums80$boy2nd), 3),
                   paste('(', round(sd(pums80$boy2nd), 3), ')', sep=''),
                   round(mean(pums80$twoboys), 3),
                   paste('(', round(sd(pums80$twoboys), 3), ')', sep=''),
                   round(mean(pums80$twogirls), 3),
                   paste('(', round(sd(pums80$twogirls), 3), ')', sep=''),
                   round(mean(pums80$samesex), 3),
                   paste('(', round(sd(pums80$samesex), 3), ')', sep=''),
                   round(mean(pums80$multi2nd), 3),
                   paste('(', round(sd(pums80$multi2nd), 3), ')', sep=''), 
                   round(mean(pums80$agem1), 3),
                   paste('(', round(sd(pums80$agem1), 3), ')', sep=''), 
                   round(mean(pums80$agefstm), 3),
                   paste('(', round(sd(pums80$agefstm), 3), ')', sep=''), 
                   round(mean(pums80$workedm), 3),
                   paste('(', round(sd(pums80$workedm), 3), ')', sep=''), 
                   round(mean(pums80$weeksm1), 3),
                   paste('(', round(sd(pums80$weeksm1), 3), ')', sep=''), 
                   round(mean(pums80$hourswm), 3),
                   paste('(', round(sd(pums80$hourswm), 3), ')', sep=''),
                   round(mean(pums80$incomem), 3),
                   paste('(', round(sd(pums80$incomem), 3), ')', sep=''),
                   nrow(pums80)
                  )

characteristics_table_2 <- data.frame('PUMS 1980' = values_column_2)
row.names(characteristics_table_2) <- row_names_column_2

stargazer(
  characteristics_table_2, 
  header = FALSE,
  summary = FALSE, 
  style = 'AER',
  title = 'Descriptive Statistics, 1980 PUMS Data',
  covariate.labels = c('Married women aged 21–35 with 2 or more children', 'Mean (Standard Deviation)'),
  notes = c('Notes: This data includes women with two or more children except for women',  'whose second birth was less than a year old when surveyed.')
)

```

## Discussion
