---
title: "A Quick and Incomplete County-Level Lithium Plot"
output: html_document
---

Note that these plots are top-coded. The average for counties reporting 100 mcg/L actually extend up to ~650 mcg/L.

```{r setup, include=FALSE}
library(tidyverse)
library(urbnmapr)
library(plotly)

lithium_fips <- read.csv("~/UT Courses/3. Spring 2019/Causal Inference/CausalInferenceCourseHomework/ResearchProject/data/lithium_water_data/US_groundwater_lithium_withFIPS.csv", stringsAsFactors=FALSE, colClasses = c(NA, NA, NA, NA, "character"))

lithium_fips_summary <- lithium_fips %>%
  group_by(county_fips) %>%
  summarize(mean.lithiumlevel = mean(Lithium.mcg.L))

lithium_fips_summary[lithium_fips_summary$mean.lithiumlevel > 100, 2] = 100

lithium_data <- left_join(lithium_fips_summary, counties, by = "county_fips") 
```


```{r lithium, echo=FALSE, warning=FALSE, fig.width = 16, fig.height = 9}
lithium_data %>%
  ggplot(aes(long, lat, group = group, fill = mean.lithiumlevel)) +
  geom_polygon(color = NA) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  labs(fill = "Groundwater Lithium Levels")
```

```{r lithium_interactive, echo=FALSE, warning=FALSE, fig.width = 16, fig.height = 9}
ggplotly(
  lithium_data %>%
  ggplot(aes(long, lat, group = group, fill = mean.lithiumlevel)) +
  geom_polygon(color = NA) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  labs(fill = "Groundwater Lithium Levels")
)
```